package org.oremif.kstats.distributions

import org.oremif.kstats.core.digamma
import org.oremif.kstats.core.exceptions.InvalidParameterException
import org.oremif.kstats.core.findQuantile
import org.oremif.kstats.core.lnBeta
import org.oremif.kstats.core.regularizedBeta
import kotlin.math.exp
import kotlin.math.ln
import kotlin.math.sqrt
import kotlin.random.Random

/**
 * Represents the Beta distribution, a continuous probability distribution defined on the
 * interval [0, 1].
 *
 * The Beta distribution is commonly used to model probabilities, proportions, and percentages
 * because its support is naturally bounded between zero and one. It is widely used as a
 * conjugate prior in Bayesian statistics -- for example, modeling the probability of success
 * in a Bernoulli trial before observing data. The two shape parameters [alpha] and [beta]
 * control the shape of the density: when both are equal, the distribution is symmetric around
 * 0.5; when they differ, the distribution skews toward one end.
 *
 * The CDF is computed via the regularized incomplete beta function, and quantiles are found
 * using Newton's method. Random samples are generated by taking the ratio of two independent
 * Gamma-distributed random variables.
 *
 * ### Example:
 * ```kotlin
 * val dist = BetaDistribution(alpha = 2.0, beta = 5.0)
 * dist.mean      // 0.2857... (skewed toward 0)
 * dist.pdf(0.3)  // 1.8522... (density at x = 0.3)
 * dist.cdf(0.5)  // 0.8906... (probability of being at most 0.5)
 *
 * val uniform = BetaDistribution.STANDARD
 * uniform.pdf(0.5) // 1.0 (flat density on [0, 1])
 * ```
 *
 * @param alpha the first shape parameter, controlling weight toward 1. Must be positive.
 * @param beta the second shape parameter, controlling weight toward 0. Must be positive.
 * @see ContinuousDistribution
 * @see GammaDistribution
 */
public class BetaDistribution(
    public val alpha: Double,
    public val beta: Double
) : ContinuousDistribution {

    init {
        if (alpha <= 0.0) throw InvalidParameterException("alpha must be positive, got $alpha")
        if (beta <= 0.0) throw InvalidParameterException("beta must be positive, got $beta")
    }

    /**
     * Computes the probability density at [x].
     *
     * Returns zero for values outside [0, 1]. At the boundaries, the density depends on the
     * shape parameters: it can be zero, finite, or infinite.
     *
     * @param x the point at which to evaluate the density.
     * @return the probability density at [x]. Always non-negative.
     */
    override fun pdf(x: Double): Double {
        if (x !in 0.0..1.0) return 0.0
        if (x == 0.0) return when {
            alpha == 1.0 -> beta
            alpha < 1.0 -> Double.POSITIVE_INFINITY
            else -> 0.0
        }
        if (x == 1.0) return when {
            beta == 1.0 -> alpha
            beta < 1.0 -> Double.POSITIVE_INFINITY
            else -> 0.0
        }
        return exp(logPdf(x))
    }

    /**
     * Computes the natural logarithm of the probability density at [x].
     *
     * Returns [Double.NEGATIVE_INFINITY] for values outside the open interval (0, 1).
     *
     * @param x the point at which to evaluate the log-density.
     * @return the natural log of the density at [x].
     */
    override fun logPdf(x: Double): Double {
        if (x <= 0.0 || x >= 1.0) return Double.NEGATIVE_INFINITY
        return (alpha - 1.0) * ln(x) + (beta - 1.0) * ln(1.0 - x) - lnBeta(alpha, beta)
    }

    /**
     * Computes the cumulative distribution function at [x].
     *
     * Returns the probability that a Beta-distributed random variable is less than or equal
     * to [x], evaluated via the regularized incomplete beta function.
     *
     * @param x the point at which to evaluate the CDF.
     * @return the cumulative probability at [x], in the range [0, 1].
     */
    override fun cdf(x: Double): Double {
        if (x <= 0.0) return 0.0
        if (x >= 1.0) return 1.0
        return regularizedBeta(x, alpha, beta)
    }

    /**
     * Computes the survival function (one minus the CDF) at [x].
     *
     * Uses a symmetry property of the regularized incomplete beta function for improved
     * numerical accuracy in the upper tail.
     *
     * @param x the point at which to evaluate the survival function.
     * @return the probability that a value exceeds [x], in the range [0, 1].
     */
    override fun sf(x: Double): Double {
        if (x <= 0.0) return 1.0
        if (x >= 1.0) return 0.0
        return regularizedBeta(1.0 - x, beta, alpha)
    }

    /** The differential entropy of this distribution. */
    override val entropy: Double get() =
        lnBeta(alpha, beta) - (alpha - 1.0) * digamma(alpha) - (beta - 1.0) * digamma(beta) +
            (alpha + beta - 2.0) * digamma(alpha + beta)

    /**
     * Computes the quantile (inverse CDF) for the given probability [p].
     *
     * Uses Newton's method seeded with the distribution mean as the initial guess.
     * The result is clamped to the open interval (0, 1).
     *
     * @param p the cumulative probability, must be in [0, 1].
     * @return the value x in [0, 1] such that `cdf(x) = p`.
     */
    override fun quantile(p: Double): Double {
        if (p !in 0.0..1.0) throw InvalidParameterException("p must be in [0, 1], got $p")
        if (p == 0.0) return 0.0
        if (p == 1.0) return 1.0
        return findQuantile(p, ::cdf, ::pdf, alpha / (alpha + beta), lowerBound = 1e-15, upperBound = 1.0 - 1e-15)
    }

    /** The mean of this distribution, equal to alpha / (alpha + beta). */
    override val mean: Double get() = alpha / (alpha + beta)

    /** The variance of this distribution, which decreases as alpha + beta increases. */
    override val variance: Double get() {
        val ab = alpha + beta
        return (alpha * beta) / (ab * ab * (ab + 1.0))
    }

    /** The skewness of this distribution. Positive when alpha < beta, negative when alpha > beta. */
    override val skewness: Double get() {
        val ab = alpha + beta
        return 2.0 * (beta - alpha) * sqrt(ab + 1.0) / ((ab + 2.0) * sqrt(alpha * beta))
    }

    /** The excess kurtosis of this distribution. */
    override val kurtosis: Double get() { // excess
        val ab = alpha + beta
        return 6.0 * (alpha * alpha * alpha - alpha * alpha * (2.0 * beta - 1.0) +
            beta * beta * (beta + 1.0) - 2.0 * alpha * beta * (beta + 2.0)) /
            (alpha * beta * (ab + 2.0) * (ab + 3.0))
    }

    /**
     * Draws a single random value from this Beta distribution.
     *
     * Generates two independent Gamma-distributed samples (one with shape [alpha], one with
     * shape [beta]) and returns their ratio. This is the standard method for Beta sampling.
     *
     * @param random the source of randomness.
     * @return a random value in the interval (0, 1).
     */
    override fun sample(random: Random): Double {
        val x = GammaDistribution(alpha, 1.0).sample(random)
        val y = GammaDistribution(beta, 1.0).sample(random)
        return x / (x + y)
    }

    /** Predefined Beta distribution instances. */
    public companion object {
        /** The standard Beta distribution with alpha = 1 and beta = 1, equivalent to the continuous uniform distribution on [0, 1]. */
        public val STANDARD: BetaDistribution = BetaDistribution(1.0, 1.0)
    }
}
