package org.oremif.kstats.distributions

import org.oremif.kstats.core.*
import org.oremif.kstats.core.exceptions.InvalidParameterException
import kotlin.math.*
import kotlin.random.Random

/**
 * Represents the Nakagami-m distribution, a continuous probability distribution defined on
 * the interval [0, +infinity).
 *
 * The Nakagami distribution models the magnitude of signals subject to multipath fading and
 * is widely used in wireless communications. If X ~ Nakagami(mu, omega), then X squared
 * follows a Gamma distribution with shape [mu] and scale omega/mu. When [mu] = 1 the
 * distribution reduces to Rayleigh, and when [mu] = 0.5 it reduces to a half-normal.
 *
 * The CDF is computed via the regularized incomplete gamma function using the Gamma
 * relationship. Quantiles are found using Newton's method with a mean-based initial guess.
 * Random samples are generated by taking the square root of a Gamma variate.
 *
 * ### Example:
 * ```kotlin
 * val dist = NakagamiDistribution(mu = 2.0, omega = 3.0)
 * dist.mean      // 1.6281... (Gamma(mu+0.5)/Gamma(mu) * sqrt(omega/mu))
 * dist.variance  // 0.3493... (omega * (1 - (Gamma(mu+0.5)/Gamma(mu))^2 / mu))
 * dist.pdf(1.5)  // 0.6694... (density at x = 1.5)
 * dist.cdf(2.0)  // 0.7452... (probability of being at most 2)
 *
 * // Rayleigh as a special case (mu = 1)
 * val rayleigh = NakagamiDistribution(mu = 1.0, omega = 1.0)
 * ```
 *
 * @property mu the shape parameter (fading parameter). Must be at least 0.5.
 * @property omega the spread parameter (average power, equal to E[X squared]). Must be positive.
 * @see ContinuousDistribution
 * @see GammaDistribution
 */
public class NakagamiDistribution(
    public val mu: Double,
    public val omega: Double,
) : ContinuousDistribution {

    init {
        if (!mu.isFinite() || mu < 0.5) throw InvalidParameterException("mu must be finite and >= 0.5, got $mu")
        if (!omega.isFinite() || omega <= 0.0) throw InvalidParameterException("omega must be finite and positive, got $omega")
    }

    // Pre-computed log normalization constant: ln(2) + mu*ln(mu) - lnGamma(mu) - mu*ln(omega)
    private val logNormConst = ln(2.0) + mu * ln(mu) - lnGamma(mu) - mu * ln(omega)

    // Gamma(mu + 0.5) / Gamma(mu), computed in log space to avoid overflow
    private val gammaRatio = exp(lnGamma(mu + 0.5) - lnGamma(mu))

    private val gammaDelegate = GammaDistribution(mu, mu / omega)

    /**
     * Computes the probability density at [x].
     *
     * Returns zero for negative values. At x = 0, the density depends on [mu]: it equals
     * `sqrt(2 / (pi * omega))` when mu is 0.5, and is zero when mu is greater than 0.5.
     *
     * @param x the point at which to evaluate the density.
     * @return the probability density at [x]. Always non-negative.
     */
    override fun pdf(x: Double): Double {
        if (x < 0.0) return 0.0
        if (x == 0.0) return if (mu == 0.5) sqrt(2.0 / (PI * omega)) else 0.0
        return exp(logPdf(x))
    }

    /**
     * Computes the natural logarithm of the probability density at [x].
     *
     * Returns [Double.NEGATIVE_INFINITY] for non-positive values.
     *
     * @param x the point at which to evaluate the log-density.
     * @return the natural log of the density at [x].
     */
    override fun logPdf(x: Double): Double {
        if (x < 0.0) return Double.NEGATIVE_INFINITY
        if (x == 0.0) return when {
            mu == 0.5 -> 0.5 * ln(2.0 / (PI * omega))
            else -> Double.NEGATIVE_INFINITY
        }
        return logNormConst + (2.0 * mu - 1.0) * ln(x) - mu * x * x / omega
    }

    /**
     * Computes the cumulative distribution function at [x].
     *
     * Uses the relationship Nakagami(mu, omega) CDF = GammaP(mu, mu * x squared / omega)
     * where GammaP is the regularized lower incomplete gamma function.
     *
     * @param x the point at which to evaluate the CDF.
     * @return the cumulative probability at [x], in the range [0, 1].
     */
    override fun cdf(x: Double): Double {
        if (x <= 0.0) return 0.0
        if (x == Double.POSITIVE_INFINITY) return 1.0
        return regularizedGammaP(mu, mu * x * x / omega)
    }

    /**
     * Computes the survival function (one minus the CDF) at [x].
     *
     * Uses the regularized upper incomplete gamma function for improved numerical accuracy
     * in the upper tail.
     *
     * @param x the point at which to evaluate the survival function.
     * @return the probability that a value exceeds [x], in the range [0, 1].
     */
    override fun sf(x: Double): Double {
        if (x <= 0.0) return 1.0
        return regularizedGammaQ(mu, mu * x * x / omega)
    }

    /**
     * Computes the quantile (inverse CDF) for the given probability [p].
     *
     * Uses Newton's method seeded with the distribution mean as the initial guess.
     *
     * @param p the cumulative probability, must be in [0, 1].
     * @return the value x >= 0 such that `cdf(x) = p`.
     */
    override fun quantile(p: Double): Double {
        if (p !in 0.0..1.0) throw InvalidParameterException("p must be in [0, 1], got $p")
        if (p == 0.0) return 0.0
        if (p == 1.0) return Double.POSITIVE_INFINITY
        return findQuantile(p, ::cdf, ::pdf, mean, lowerBound = 0.0)
    }

    /** The mean of this distribution. */
    override val mean: Double get() = gammaRatio * sqrt(omega / mu)

    /** The variance of this distribution. */
    override val variance: Double get() = omega * (1.0 - gammaRatio * gammaRatio / mu)

    /** The skewness of this distribution, computed from raw moments via the Gamma relationship. */
    override val skewness: Double
        get() {
            val m1 = mean
            val gammaRatio3 = exp(lnGamma(mu + 1.5) - lnGamma(mu))
            val m3 = gammaRatio3 * (omega / mu).pow(1.5) // E[X^3]
            val v = variance
            val sd = sqrt(v)
            return (m3 - 3.0 * m1 * v - m1 * m1 * m1) / (sd * sd * sd)
        }

    /** The excess kurtosis of this distribution, computed from raw moments via the Gamma relationship. */
    override val kurtosis: Double
        get() {
            val m1 = mean
            val m2 = omega // E[X^2]
            val gammaRatio3 = exp(lnGamma(mu + 1.5) - lnGamma(mu))
            val m3 = gammaRatio3 * (omega / mu).pow(1.5) // E[X^3]
            val m4 = (mu + 1.0) * omega * omega / mu // E[X^4] = Gamma(mu+2)/Gamma(mu) * (omega/mu)^2
            val v = variance
            return (m4 - 4.0 * m1 * m3 + 6.0 * m1 * m1 * m2 - 3.0 * m1 * m1 * m1 * m1) / (v * v) - 3.0
        }

    /** The differential entropy of this distribution. */
    override val entropy: Double =
        lnGamma(mu) + mu - (mu - 0.5) * digamma(mu) - 0.5 * ln(mu) - ln(2.0) + 0.5 * ln(omega)

    /**
     * Draws a single random value from this Nakagami distribution.
     *
     * Samples from Gamma(mu, rate = mu/omega) and returns the square root, exploiting the
     * relationship X = sqrt(Y) where Y ~ Gamma(mu, mu/omega).
     *
     * @param random the source of randomness.
     * @return a random non-negative value drawn from this distribution.
     */
    override fun sample(random: Random): Double {
        return sqrt(gammaDelegate.sample(random))
    }
}
