package org.oremif.kstats.descriptive

import org.oremif.kstats.core.exceptions.InsufficientDataException
import org.oremif.kstats.core.exceptions.InvalidParameterException
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

internal class QuantilesTest {

    private val tol = 1e-10

    // ── Basic: quantile known values per HF method (data = [2, 4, 6, 8, 10]) ──
    //
    // Reference values were generated by simulating the kstats Hyndman-Fan
    // implementation (position formulas and rounding rules). Where kstats and
    // numpy differ (e.g. banker's rounding in HF3, discontinuity handling in HF2),
    // the kstats definition is authoritative.

    private val data5 = doubleArrayOf(2.0, 4.0, 6.0, 8.0, 10.0)

    @Test
    fun testQuantileInvertedCdfKnownValues() {
        // HF1: h = n*q + 0.5, result = x_(ceil(h - 0.5))
        assertEquals(2.0, data5.quantile(0.0, QuantileMethod.INVERTED_CDF), tol)
        assertEquals(2.0, data5.quantile(0.1, QuantileMethod.INVERTED_CDF), tol)
        assertEquals(4.0, data5.quantile(0.25, QuantileMethod.INVERTED_CDF), tol)
        assertEquals(4.0, data5.quantile(0.3, QuantileMethod.INVERTED_CDF), tol)
        assertEquals(6.0, data5.quantile(0.5, QuantileMethod.INVERTED_CDF), tol)
        assertEquals(8.0, data5.quantile(0.75, QuantileMethod.INVERTED_CDF), tol)
        assertEquals(10.0, data5.quantile(0.9, QuantileMethod.INVERTED_CDF), tol)
        assertEquals(10.0, data5.quantile(1.0, QuantileMethod.INVERTED_CDF), tol)
    }

    @Test
    fun testQuantileAveragedInvertedCdfKnownValues() {
        // HF2: h = n*q + 0.5, averaging at integer discontinuities of h-0.5
        // Note: at q=0, h=0.5, h-0.5=0.0 is integer => discontinuity => average x[0] and x[1]
        assertEquals(3.0, data5.quantile(0.0, QuantileMethod.AVERAGED_INVERTED_CDF), tol)
        assertEquals(2.0, data5.quantile(0.1, QuantileMethod.AVERAGED_INVERTED_CDF), tol)
        assertEquals(4.0, data5.quantile(0.25, QuantileMethod.AVERAGED_INVERTED_CDF), tol)
        assertEquals(4.0, data5.quantile(0.3, QuantileMethod.AVERAGED_INVERTED_CDF), tol)
        assertEquals(6.0, data5.quantile(0.5, QuantileMethod.AVERAGED_INVERTED_CDF), tol)
        assertEquals(8.0, data5.quantile(0.75, QuantileMethod.AVERAGED_INVERTED_CDF), tol)
        assertEquals(10.0, data5.quantile(0.9, QuantileMethod.AVERAGED_INVERTED_CDF), tol)
        assertEquals(10.0, data5.quantile(1.0, QuantileMethod.AVERAGED_INVERTED_CDF), tol)
    }

    @Test
    fun testQuantileClosestObservationKnownValues() {
        // HF3: h = n*q, banker's rounding (ties to even)
        // 2.5 rounds to 2 (even), 4.5 rounds to 4 (even)
        assertEquals(2.0, data5.quantile(0.0, QuantileMethod.CLOSEST_OBSERVATION), tol)
        assertEquals(2.0, data5.quantile(0.1, QuantileMethod.CLOSEST_OBSERVATION), tol)
        assertEquals(2.0, data5.quantile(0.25, QuantileMethod.CLOSEST_OBSERVATION), tol)
        assertEquals(4.0, data5.quantile(0.3, QuantileMethod.CLOSEST_OBSERVATION), tol)
        assertEquals(4.0, data5.quantile(0.5, QuantileMethod.CLOSEST_OBSERVATION), tol) // h=2.5 -> round=2 (even)
        assertEquals(8.0, data5.quantile(0.75, QuantileMethod.CLOSEST_OBSERVATION), tol)
        assertEquals(8.0, data5.quantile(0.9, QuantileMethod.CLOSEST_OBSERVATION), tol) // h=4.5 -> round=4 (even)
        assertEquals(10.0, data5.quantile(1.0, QuantileMethod.CLOSEST_OBSERVATION), tol)
    }

    @Test
    fun testQuantileInterpolatedInvertedCdfKnownValues() {
        // HF4: h = n*q, linear interpolation
        // numpy: np.quantile([2,4,6,8,10], q, method='interpolated_inverted_cdf')
        assertEquals(2.0, data5.quantile(0.0, QuantileMethod.INTERPOLATED_INVERTED_CDF), tol)
        assertEquals(2.0, data5.quantile(0.1, QuantileMethod.INTERPOLATED_INVERTED_CDF), tol)
        assertEquals(2.5, data5.quantile(0.25, QuantileMethod.INTERPOLATED_INVERTED_CDF), tol)
        assertEquals(3.0, data5.quantile(0.3, QuantileMethod.INTERPOLATED_INVERTED_CDF), tol)
        assertEquals(5.0, data5.quantile(0.5, QuantileMethod.INTERPOLATED_INVERTED_CDF), tol)
        assertEquals(7.5, data5.quantile(0.75, QuantileMethod.INTERPOLATED_INVERTED_CDF), tol)
        assertEquals(9.0, data5.quantile(0.9, QuantileMethod.INTERPOLATED_INVERTED_CDF), tol)
        assertEquals(10.0, data5.quantile(1.0, QuantileMethod.INTERPOLATED_INVERTED_CDF), tol)
    }

    @Test
    fun testQuantileHazenKnownValues() {
        // HF5: h = n*q + 0.5, linear interpolation
        // numpy: np.quantile([2,4,6,8,10], q, method='hazen')
        assertEquals(2.0, data5.quantile(0.0, QuantileMethod.HAZEN), tol)
        assertEquals(2.0, data5.quantile(0.1, QuantileMethod.HAZEN), tol)
        assertEquals(3.5, data5.quantile(0.25, QuantileMethod.HAZEN), tol)
        assertEquals(4.0, data5.quantile(0.3, QuantileMethod.HAZEN), tol)
        assertEquals(6.0, data5.quantile(0.5, QuantileMethod.HAZEN), tol)
        assertEquals(8.5, data5.quantile(0.75, QuantileMethod.HAZEN), tol)
        assertEquals(10.0, data5.quantile(0.9, QuantileMethod.HAZEN), tol)
        assertEquals(10.0, data5.quantile(1.0, QuantileMethod.HAZEN), tol)
    }

    @Test
    fun testQuantileWeibullKnownValues() {
        // HF6: h = (n+1)*q, linear interpolation
        // numpy: np.quantile([2,4,6,8,10], q, method='weibull')
        assertEquals(2.0, data5.quantile(0.0, QuantileMethod.WEIBULL), tol)
        assertEquals(2.0, data5.quantile(0.1, QuantileMethod.WEIBULL), tol)
        assertEquals(3.0, data5.quantile(0.25, QuantileMethod.WEIBULL), tol)
        assertEquals(3.6, data5.quantile(0.3, QuantileMethod.WEIBULL), tol)
        assertEquals(6.0, data5.quantile(0.5, QuantileMethod.WEIBULL), tol)
        assertEquals(9.0, data5.quantile(0.75, QuantileMethod.WEIBULL), tol)
        assertEquals(10.0, data5.quantile(0.9, QuantileMethod.WEIBULL), tol)
        assertEquals(10.0, data5.quantile(1.0, QuantileMethod.WEIBULL), tol)
    }

    @Test
    fun testQuantileLinearKnownValues() {
        // HF7: h = (n-1)*q + 1, linear interpolation
        // numpy: np.quantile([2,4,6,8,10], q, method='linear')
        assertEquals(2.0, data5.quantile(0.0, QuantileMethod.LINEAR), tol)
        assertEquals(2.8, data5.quantile(0.1, QuantileMethod.LINEAR), tol)
        assertEquals(4.0, data5.quantile(0.25, QuantileMethod.LINEAR), tol)
        assertEquals(4.4, data5.quantile(0.3, QuantileMethod.LINEAR), tol)
        assertEquals(6.0, data5.quantile(0.5, QuantileMethod.LINEAR), tol)
        assertEquals(8.0, data5.quantile(0.75, QuantileMethod.LINEAR), tol)
        assertEquals(9.2, data5.quantile(0.9, QuantileMethod.LINEAR), tol)
        assertEquals(10.0, data5.quantile(1.0, QuantileMethod.LINEAR), tol)
    }

    @Test
    fun testQuantileMedianUnbiasedKnownValues() {
        // HF8: h = (n + 1/3)*q + 1/3, linear interpolation
        // numpy: np.quantile([2,4,6,8,10], q, method='median_unbiased')
        assertEquals(2.0, data5.quantile(0.0, QuantileMethod.MEDIAN_UNBIASED), tol)
        assertEquals(2.0, data5.quantile(0.1, QuantileMethod.MEDIAN_UNBIASED), tol)
        assertEquals(3.33333333333333, data5.quantile(0.25, QuantileMethod.MEDIAN_UNBIASED), tol)
        assertEquals(3.86666666666667, data5.quantile(0.3, QuantileMethod.MEDIAN_UNBIASED), tol)
        assertEquals(6.0, data5.quantile(0.5, QuantileMethod.MEDIAN_UNBIASED), tol)
        assertEquals(8.66666666666667, data5.quantile(0.75, QuantileMethod.MEDIAN_UNBIASED), tol)
        assertEquals(10.0, data5.quantile(0.9, QuantileMethod.MEDIAN_UNBIASED), tol)
        assertEquals(10.0, data5.quantile(1.0, QuantileMethod.MEDIAN_UNBIASED), tol)
    }

    @Test
    fun testQuantileNormalUnbiasedKnownValues() {
        // HF9: h = (n + 1/4)*q + 3/8, linear interpolation
        // numpy: np.quantile([2,4,6,8,10], q, method='normal_unbiased')
        assertEquals(2.0, data5.quantile(0.0, QuantileMethod.NORMAL_UNBIASED), tol)
        assertEquals(2.0, data5.quantile(0.1, QuantileMethod.NORMAL_UNBIASED), tol)
        assertEquals(3.375, data5.quantile(0.25, QuantileMethod.NORMAL_UNBIASED), tol)
        assertEquals(3.9, data5.quantile(0.3, QuantileMethod.NORMAL_UNBIASED), tol)
        assertEquals(6.0, data5.quantile(0.5, QuantileMethod.NORMAL_UNBIASED), tol)
        assertEquals(8.625, data5.quantile(0.75, QuantileMethod.NORMAL_UNBIASED), tol)
        assertEquals(10.0, data5.quantile(0.9, QuantileMethod.NORMAL_UNBIASED), tol)
        assertEquals(10.0, data5.quantile(1.0, QuantileMethod.NORMAL_UNBIASED), tol)
    }

    @Test
    fun testQuantileLowerKnownValues() {
        // h = (n-1)*q + 1, result = x_(floor(h))
        // numpy: np.quantile([2,4,6,8,10], q, method='lower')
        assertEquals(2.0, data5.quantile(0.0, QuantileMethod.LOWER), tol)
        assertEquals(2.0, data5.quantile(0.1, QuantileMethod.LOWER), tol)
        assertEquals(4.0, data5.quantile(0.25, QuantileMethod.LOWER), tol)
        assertEquals(4.0, data5.quantile(0.3, QuantileMethod.LOWER), tol)
        assertEquals(6.0, data5.quantile(0.5, QuantileMethod.LOWER), tol)
        assertEquals(8.0, data5.quantile(0.75, QuantileMethod.LOWER), tol)
        assertEquals(8.0, data5.quantile(0.9, QuantileMethod.LOWER), tol)
        assertEquals(10.0, data5.quantile(1.0, QuantileMethod.LOWER), tol)
    }

    @Test
    fun testQuantileHigherKnownValues() {
        // h = (n-1)*q + 1, result = x_(ceil(h))
        // numpy: np.quantile([2,4,6,8,10], q, method='higher')
        assertEquals(2.0, data5.quantile(0.0, QuantileMethod.HIGHER), tol)
        assertEquals(4.0, data5.quantile(0.1, QuantileMethod.HIGHER), tol)
        assertEquals(4.0, data5.quantile(0.25, QuantileMethod.HIGHER), tol)
        assertEquals(6.0, data5.quantile(0.3, QuantileMethod.HIGHER), tol)
        assertEquals(6.0, data5.quantile(0.5, QuantileMethod.HIGHER), tol)
        assertEquals(8.0, data5.quantile(0.75, QuantileMethod.HIGHER), tol)
        assertEquals(10.0, data5.quantile(0.9, QuantileMethod.HIGHER), tol)
        assertEquals(10.0, data5.quantile(1.0, QuantileMethod.HIGHER), tol)
    }

    @Test
    fun testQuantileNearestKnownValues() {
        // h = (n-1)*q + 1, result = x_(round half up)
        // numpy: np.quantile([2,4,6,8,10], q, method='nearest')
        assertEquals(2.0, data5.quantile(0.0, QuantileMethod.NEAREST), tol)
        assertEquals(2.0, data5.quantile(0.1, QuantileMethod.NEAREST), tol)
        assertEquals(4.0, data5.quantile(0.25, QuantileMethod.NEAREST), tol)
        assertEquals(4.0, data5.quantile(0.3, QuantileMethod.NEAREST), tol)
        assertEquals(6.0, data5.quantile(0.5, QuantileMethod.NEAREST), tol)
        assertEquals(8.0, data5.quantile(0.75, QuantileMethod.NEAREST), tol)
        assertEquals(10.0, data5.quantile(0.9, QuantileMethod.NEAREST), tol)
        assertEquals(10.0, data5.quantile(1.0, QuantileMethod.NEAREST), tol)
    }

    @Test
    fun testQuantileMidpointKnownValues() {
        // h = (n-1)*q + 1, result = (x_(floor) + x_(ceil)) / 2
        // numpy: np.quantile([2,4,6,8,10], q, method='midpoint')
        assertEquals(2.0, data5.quantile(0.0, QuantileMethod.MIDPOINT), tol)
        assertEquals(3.0, data5.quantile(0.1, QuantileMethod.MIDPOINT), tol)
        assertEquals(4.0, data5.quantile(0.25, QuantileMethod.MIDPOINT), tol)
        assertEquals(5.0, data5.quantile(0.3, QuantileMethod.MIDPOINT), tol)
        assertEquals(6.0, data5.quantile(0.5, QuantileMethod.MIDPOINT), tol)
        assertEquals(8.0, data5.quantile(0.75, QuantileMethod.MIDPOINT), tol)
        assertEquals(9.0, data5.quantile(0.9, QuantileMethod.MIDPOINT), tol)
        assertEquals(10.0, data5.quantile(1.0, QuantileMethod.MIDPOINT), tol)
    }

    // ── Basic: larger dataset for interpolation-heavy methods ───────────────────

    private val data10 = doubleArrayOf(1.0, 3.0, 5.0, 7.0, 9.0, 11.0, 13.0, 15.0, 17.0, 19.0)

    @Test
    fun testQuantileLinearLargerDataKnownValues() {
        // numpy: np.quantile([1,3,...,19], q, method='linear')
        assertEquals(1.9, data10.quantile(0.05, QuantileMethod.LINEAR), tol)
        assertEquals(2.8, data10.quantile(0.1, QuantileMethod.LINEAR), tol)
        assertEquals(5.5, data10.quantile(0.25, QuantileMethod.LINEAR), tol)
        assertEquals(6.4, data10.quantile(0.3, QuantileMethod.LINEAR), tol)
        assertEquals(10.0, data10.quantile(0.5, QuantileMethod.LINEAR), tol)
        assertEquals(14.5, data10.quantile(0.75, QuantileMethod.LINEAR), tol)
        assertEquals(17.2, data10.quantile(0.9, QuantileMethod.LINEAR), tol)
        assertEquals(18.1, data10.quantile(0.95, QuantileMethod.LINEAR), tol)
    }

    @Test
    fun testQuantileMedianUnbiasedLargerDataKnownValues() {
        // numpy: np.quantile([1,3,...,19], q, method='median_unbiased')
        assertEquals(1.73333333333333, data10.quantile(0.1, QuantileMethod.MEDIAN_UNBIASED), tol)
        assertEquals(4.83333333333333, data10.quantile(0.25, QuantileMethod.MEDIAN_UNBIASED), tol)
        assertEquals(5.86666666666667, data10.quantile(0.3, QuantileMethod.MEDIAN_UNBIASED), tol)
        assertEquals(10.0, data10.quantile(0.5, QuantileMethod.MEDIAN_UNBIASED), tol)
        assertEquals(15.1666666666667, data10.quantile(0.75, QuantileMethod.MEDIAN_UNBIASED), tol)
        assertEquals(18.2666666666667, data10.quantile(0.9, QuantileMethod.MEDIAN_UNBIASED), tol)
    }

    @Test
    fun testQuantileNormalUnbiasedLargerDataKnownValues() {
        // numpy: np.quantile([1,3,...,19], q, method='normal_unbiased')
        assertEquals(1.8, data10.quantile(0.1, QuantileMethod.NORMAL_UNBIASED), tol)
        assertEquals(4.875, data10.quantile(0.25, QuantileMethod.NORMAL_UNBIASED), tol)
        assertEquals(5.9, data10.quantile(0.3, QuantileMethod.NORMAL_UNBIASED), tol)
        assertEquals(10.0, data10.quantile(0.5, QuantileMethod.NORMAL_UNBIASED), tol)
        assertEquals(15.125, data10.quantile(0.75, QuantileMethod.NORMAL_UNBIASED), tol)
        assertEquals(18.2, data10.quantile(0.9, QuantileMethod.NORMAL_UNBIASED), tol)
    }

    @Test
    fun testQuantileWeibullLargerDataKnownValues() {
        // numpy: np.quantile([1,3,...,19], q, method='weibull')
        assertEquals(1.2, data10.quantile(0.1, QuantileMethod.WEIBULL), tol)
        assertEquals(4.5, data10.quantile(0.25, QuantileMethod.WEIBULL), tol)
        assertEquals(5.6, data10.quantile(0.3, QuantileMethod.WEIBULL), tol)
        assertEquals(10.0, data10.quantile(0.5, QuantileMethod.WEIBULL), tol)
        assertEquals(15.5, data10.quantile(0.75, QuantileMethod.WEIBULL), tol)
        assertEquals(18.8, data10.quantile(0.9, QuantileMethod.WEIBULL), tol)
    }

    // ── Basic: even-size data [1, 2, 3, 4] ────────────────────────────────────

    private val data4 = doubleArrayOf(1.0, 2.0, 3.0, 4.0)

    @Test
    fun testQuantileEvenSizeLinearKnownValues() {
        // numpy: np.quantile([1,2,3,4], q, method='linear')
        assertEquals(1.0, data4.quantile(0.0, QuantileMethod.LINEAR), tol)
        assertEquals(1.75, data4.quantile(0.25, QuantileMethod.LINEAR), tol)
        assertEquals(2.5, data4.quantile(0.5, QuantileMethod.LINEAR), tol)
        assertEquals(3.25, data4.quantile(0.75, QuantileMethod.LINEAR), tol)
        assertEquals(4.0, data4.quantile(1.0, QuantileMethod.LINEAR), tol)
    }

    @Test
    fun testQuantileEvenSizeAllMethodsAtMedian() {
        // kstats implementation values for q=0.5 on [1,2,3,4]
        assertEquals(2.0, data4.quantile(0.5, QuantileMethod.INVERTED_CDF), tol)
        assertEquals(2.5, data4.quantile(0.5, QuantileMethod.AVERAGED_INVERTED_CDF), tol)
        assertEquals(2.0, data4.quantile(0.5, QuantileMethod.CLOSEST_OBSERVATION), tol)
        assertEquals(2.0, data4.quantile(0.5, QuantileMethod.INTERPOLATED_INVERTED_CDF), tol)
        assertEquals(2.5, data4.quantile(0.5, QuantileMethod.HAZEN), tol)
        assertEquals(2.5, data4.quantile(0.5, QuantileMethod.WEIBULL), tol)
        assertEquals(2.5, data4.quantile(0.5, QuantileMethod.LINEAR), tol)
        assertEquals(2.5, data4.quantile(0.5, QuantileMethod.MEDIAN_UNBIASED), tol)
        assertEquals(2.5, data4.quantile(0.5, QuantileMethod.NORMAL_UNBIASED), tol)
        assertEquals(2.0, data4.quantile(0.5, QuantileMethod.LOWER), tol)
        assertEquals(3.0, data4.quantile(0.5, QuantileMethod.HIGHER), tol)
        assertEquals(3.0, data4.quantile(0.5, QuantileMethod.NEAREST), tol)
        assertEquals(2.5, data4.quantile(0.5, QuantileMethod.MIDPOINT), tol)
    }

    @Test
    fun testQuantileEvenSizeQ25AllMethods() {
        // kstats implementation values for q=0.25 on [1,2,3,4]
        assertEquals(1.0, data4.quantile(0.25, QuantileMethod.INVERTED_CDF), tol)
        assertEquals(1.5, data4.quantile(0.25, QuantileMethod.AVERAGED_INVERTED_CDF), tol)
        assertEquals(1.0, data4.quantile(0.25, QuantileMethod.CLOSEST_OBSERVATION), tol)
        assertEquals(1.0, data4.quantile(0.25, QuantileMethod.INTERPOLATED_INVERTED_CDF), tol)
        assertEquals(1.5, data4.quantile(0.25, QuantileMethod.HAZEN), tol)
        assertEquals(1.25, data4.quantile(0.25, QuantileMethod.WEIBULL), tol)
        assertEquals(1.75, data4.quantile(0.25, QuantileMethod.LINEAR), tol)
        assertEquals(1.41666666666667, data4.quantile(0.25, QuantileMethod.MEDIAN_UNBIASED), tol)
        assertEquals(1.4375, data4.quantile(0.25, QuantileMethod.NORMAL_UNBIASED), tol)
        assertEquals(1.0, data4.quantile(0.25, QuantileMethod.LOWER), tol)
        assertEquals(2.0, data4.quantile(0.25, QuantileMethod.HIGHER), tol)
        assertEquals(2.0, data4.quantile(0.25, QuantileMethod.NEAREST), tol)
        assertEquals(1.5, data4.quantile(0.25, QuantileMethod.MIDPOINT), tol)
    }

    // ── Basic: percentile known values ─────────────────────────────────────────

    @Test
    fun testPercentileMedian() {
        val data = doubleArrayOf(1.0, 2.0, 3.0, 4.0, 5.0)
        // numpy: np.percentile([1,2,3,4,5], 50) = 3.0
        assertEquals(3.0, data.toList().percentile(50.0), tol)
    }

    @Test
    fun testPercentileLinearInterpolation() {
        val data = doubleArrayOf(1.0, 2.0, 3.0, 4.0)
        // numpy: np.percentile([1,2,3,4], 25) = 1.75
        assertEquals(1.75, data.toList().percentile(25.0), tol)
    }

    @Test
    fun testPercentileEquivalentToQuantile() {
        // percentile(p) should always equal quantile(p/100)
        val data = doubleArrayOf(2.0, 4.0, 6.0, 8.0, 10.0)
        for (p in listOf(0.0, 25.0, 50.0, 75.0, 90.0, 100.0)) {
            assertEquals(
                data.quantile(p / 100.0, QuantileMethod.LINEAR),
                data.percentile(p, QuantileMethod.LINEAR),
                tol,
                "percentile($p) should equal quantile(${p / 100.0})"
            )
        }
    }

    @Test
    fun testPercentileLowerHigherMethods() {
        val data = doubleArrayOf(1.0, 2.0, 3.0, 4.0)
        // numpy: np.percentile([1,2,3,4], 25, method='lower') = 1.0
        assertEquals(1.0, data.toList().percentile(25.0, QuantileMethod.LOWER), tol)
        // numpy: np.percentile([1,2,3,4], 25, method='higher') = 2.0
        assertEquals(2.0, data.toList().percentile(25.0, QuantileMethod.HIGHER), tol)
    }

    // ── Basic: quartiles known values ──────────────────────────────────────────

    @Test
    fun testQuartilesLinearKnownValues() {
        val data = doubleArrayOf(1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0)
        // numpy: np.quantile([1..10], [0.25, 0.5, 0.75], method='linear')
        val (q1, q2, q3) = data.quartiles(QuantileMethod.LINEAR)
        assertEquals(3.25, q1, tol)
        assertEquals(5.5, q2, tol)
        assertEquals(7.75, q3, tol)
    }

    @Test
    fun testQuartilesMedianEqualsQ2() {
        val data = doubleArrayOf(1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0)
        val (_, q2, _) = data.quartiles(QuantileMethod.LINEAR)
        assertEquals(q2, data.median(), tol)
    }

    @Test
    fun testQuartilesOrdering() {
        val data = doubleArrayOf(1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0)
        for (method in QuantileMethod.entries) {
            val (q1, q2, q3) = data.quartiles(method)
            assertTrue(q1 <= q2, "Q1 <= Q2 for $method")
            assertTrue(q2 <= q3, "Q2 <= Q3 for $method")
        }
    }

    // ── Basic: quantileSelect known values ─────────────────────────────────────

    @Test
    fun testQuantileSelectLowerKnownValues() {
        val data = listOf(10, 30, 50, 70, 90)
        assertEquals(10, data.quantileSelect(0.0, QuantileMethod.LOWER))
        assertEquals(10, data.quantileSelect(0.1, QuantileMethod.LOWER))
        assertEquals(30, data.quantileSelect(0.25, QuantileMethod.LOWER))
        assertEquals(50, data.quantileSelect(0.5, QuantileMethod.LOWER))
        assertEquals(70, data.quantileSelect(0.75, QuantileMethod.LOWER))
        assertEquals(90, data.quantileSelect(1.0, QuantileMethod.LOWER))
    }

    @Test
    fun testQuantileSelectHigherKnownValues() {
        val data = listOf(10, 30, 50, 70, 90)
        assertEquals(10, data.quantileSelect(0.0, QuantileMethod.HIGHER))
        assertEquals(30, data.quantileSelect(0.1, QuantileMethod.HIGHER))
        assertEquals(30, data.quantileSelect(0.25, QuantileMethod.HIGHER))
        assertEquals(50, data.quantileSelect(0.5, QuantileMethod.HIGHER))
        assertEquals(70, data.quantileSelect(0.75, QuantileMethod.HIGHER))
        assertEquals(90, data.quantileSelect(1.0, QuantileMethod.HIGHER))
    }

    @Test
    fun testQuantileSelectNearestKnownValues() {
        val data = listOf(10, 30, 50, 70, 90)
        assertEquals(10, data.quantileSelect(0.0, QuantileMethod.NEAREST))
        assertEquals(10, data.quantileSelect(0.1, QuantileMethod.NEAREST))
        assertEquals(30, data.quantileSelect(0.25, QuantileMethod.NEAREST))
        assertEquals(50, data.quantileSelect(0.5, QuantileMethod.NEAREST))
        assertEquals(70, data.quantileSelect(0.75, QuantileMethod.NEAREST))
        assertEquals(90, data.quantileSelect(1.0, QuantileMethod.NEAREST))
    }

    @Test
    fun testQuantileSelectInvertedCdfKnownValues() {
        val data = listOf(10, 30, 50, 70, 90)
        assertEquals(10, data.quantileSelect(0.0, QuantileMethod.INVERTED_CDF))
        assertEquals(10, data.quantileSelect(0.1, QuantileMethod.INVERTED_CDF))
        assertEquals(30, data.quantileSelect(0.25, QuantileMethod.INVERTED_CDF))
        assertEquals(50, data.quantileSelect(0.5, QuantileMethod.INVERTED_CDF))
        assertEquals(70, data.quantileSelect(0.75, QuantileMethod.INVERTED_CDF))
        assertEquals(90, data.quantileSelect(1.0, QuantileMethod.INVERTED_CDF))
    }

    @Test
    fun testQuantileSelectClosestObservationKnownValues() {
        val data = listOf(10, 30, 50, 70, 90)
        // HF3 with banker's rounding (ties to even): h=n*q
        assertEquals(10, data.quantileSelect(0.0, QuantileMethod.CLOSEST_OBSERVATION))
        assertEquals(10, data.quantileSelect(0.1, QuantileMethod.CLOSEST_OBSERVATION))
        // h=1.25, round=1 -> data[0]=10
        assertEquals(10, data.quantileSelect(0.25, QuantileMethod.CLOSEST_OBSERVATION))
        // h=2.5, bankersRound(2.5)=2 (even) -> data[1]=30
        assertEquals(30, data.quantileSelect(0.5, QuantileMethod.CLOSEST_OBSERVATION))
        // h=3.75, round=4 -> data[3]=70
        assertEquals(70, data.quantileSelect(0.75, QuantileMethod.CLOSEST_OBSERVATION))
        assertEquals(90, data.quantileSelect(1.0, QuantileMethod.CLOSEST_OBSERVATION))
    }

    // ── Basic: percentileSelect known values ───────────────────────────────────

    @Test
    fun testPercentileSelectEquivalentToQuantileSelect() {
        val data = listOf("a", "b", "c", "d", "e")
        for (p in listOf(0.0, 10.0, 25.0, 50.0, 75.0, 100.0)) {
            assertEquals(
                data.quantileSelect(p / 100.0, QuantileMethod.NEAREST),
                data.percentileSelect(p, QuantileMethod.NEAREST),
                "percentileSelect($p) should equal quantileSelect(${p / 100.0})"
            )
        }
    }

    @Test
    fun testPercentileSelectWithStrings() {
        val data = listOf("alpha", "bravo", "charlie", "delta", "echo")
        // NEAREST at 50th percentile -> median element
        assertEquals("charlie", data.percentileSelect(50.0))
    }

    // ── Basic: Iterable and Sequence overloads ─────────────────────────────────

    @Test
    fun testQuantileIterableEqualsDoubleArray() {
        val arr = doubleArrayOf(3.0, 1.0, 4.0, 1.0, 5.0, 9.0, 2.0, 6.0)
        val list = arr.toList()
        for (method in QuantileMethod.entries) {
            for (q in listOf(0.0, 0.25, 0.5, 0.75, 1.0)) {
                assertEquals(
                    arr.quantile(q, method),
                    list.quantile(q, method),
                    tol,
                    "Iterable.quantile($q, $method) should equal DoubleArray.quantile"
                )
            }
        }
    }

    @Test
    fun testQuantileSequenceEqualsDoubleArray() {
        val arr = doubleArrayOf(3.0, 1.0, 4.0, 1.0, 5.0, 9.0, 2.0, 6.0)
        val seq = arr.asSequence()
        for (q in listOf(0.0, 0.25, 0.5, 0.75, 1.0)) {
            assertEquals(
                arr.quantile(q, QuantileMethod.LINEAR),
                seq.quantile(q, QuantileMethod.LINEAR),
                tol,
                "Sequence.quantile($q) should equal DoubleArray.quantile"
            )
        }
    }

    @Test
    fun testPercentileSequenceEqualsDoubleArray() {
        val arr = doubleArrayOf(3.0, 1.0, 4.0, 1.0, 5.0, 9.0, 2.0, 6.0)
        val seq = arr.asSequence()
        for (p in listOf(0.0, 25.0, 50.0, 75.0, 100.0)) {
            assertEquals(
                arr.percentile(p, QuantileMethod.LINEAR),
                seq.percentile(p, QuantileMethod.LINEAR),
                tol,
                "Sequence.percentile($p) should equal DoubleArray.percentile"
            )
        }
    }

    @Test
    fun testQuartilesSequenceEqualsDoubleArray() {
        val arr = doubleArrayOf(3.0, 1.0, 4.0, 1.0, 5.0, 9.0, 2.0, 6.0)
        val (aq1, aq2, aq3) = arr.quartiles(QuantileMethod.LINEAR)
        val (sq1, sq2, sq3) = arr.asSequence().quartiles(QuantileMethod.LINEAR)
        assertEquals(aq1, sq1, tol)
        assertEquals(aq2, sq2, tol)
        assertEquals(aq3, sq3, tol)
    }

    // ── Basic: data with repeated values ───────────────────────────────────────

    @Test
    fun testQuantileRepeatedValuesLinear() {
        val data = doubleArrayOf(1.0, 1.0, 2.0, 3.0, 3.0, 3.0)
        // numpy: np.quantile([1,1,2,3,3,3], q, method='linear')
        assertEquals(1.25, data.quantile(0.25, QuantileMethod.LINEAR), tol)
        assertEquals(2.5, data.quantile(0.5, QuantileMethod.LINEAR), tol)
        assertEquals(3.0, data.quantile(0.75, QuantileMethod.LINEAR), tol)
    }

    @Test
    fun testQuantileRepeatedValuesDiscrete() {
        val data = doubleArrayOf(1.0, 1.0, 2.0, 3.0, 3.0, 3.0)
        // numpy: np.quantile([1,1,2,3,3,3], q, method=...)
        assertEquals(1.0, data.quantile(0.25, QuantileMethod.LOWER), tol)
        assertEquals(2.0, data.quantile(0.25, QuantileMethod.HIGHER), tol)
        assertEquals(1.0, data.quantile(0.25, QuantileMethod.NEAREST), tol)
        assertEquals(1.5, data.quantile(0.25, QuantileMethod.MIDPOINT), tol)
        assertEquals(1.0, data.quantile(0.25, QuantileMethod.INVERTED_CDF), tol)
    }

    // ── Edge: boundary quantile values q=0 and q=1 ────────────────────────────

    @Test
    fun testQuantileBoundaryQ0Q1() {
        val data = doubleArrayOf(1.0, 2.0, 3.0, 4.0, 5.0)
        // Most methods return min at q=0 and max at q=1
        val methodsReturningMinMax = listOf(
            QuantileMethod.INVERTED_CDF,
            QuantileMethod.CLOSEST_OBSERVATION,
            QuantileMethod.INTERPOLATED_INVERTED_CDF,
            QuantileMethod.HAZEN,
            QuantileMethod.WEIBULL,
            QuantileMethod.LINEAR,
            QuantileMethod.MEDIAN_UNBIASED,
            QuantileMethod.NORMAL_UNBIASED,
            QuantileMethod.LOWER,
            QuantileMethod.HIGHER,
            QuantileMethod.NEAREST,
            QuantileMethod.MIDPOINT,
        )
        for (method in methodsReturningMinMax) {
            assertEquals(1.0, data.quantile(0.0, method), tol, "quantile(0, $method) should be min")
            assertEquals(5.0, data.quantile(1.0, method), tol, "quantile(1, $method) should be max")
        }
    }

    @Test
    fun testQuantileAveragedInvertedCdfBoundary() {
        // AVERAGED_INVERTED_CDF at q=0 may not return min due to discontinuity averaging
        val data = doubleArrayOf(1.0, 2.0, 3.0, 4.0, 5.0)
        // h=0.5, h-0.5=0, is integer, discontinuity: average x[0] and x[1] = 1.5
        assertEquals(1.5, data.quantile(0.0, QuantileMethod.AVERAGED_INVERTED_CDF), tol)
        assertEquals(5.0, data.quantile(1.0, QuantileMethod.AVERAGED_INVERTED_CDF), tol)
    }

    // ── Edge: single element ───────────────────────────────────────────────────

    @Test
    fun testQuantileSingleElement() {
        val data = doubleArrayOf(42.0)
        for (method in QuantileMethod.entries) {
            for (q in listOf(0.0, 0.25, 0.5, 0.75, 1.0)) {
                assertEquals(
                    42.0, data.quantile(q, method), tol,
                    "Single element quantile($q, $method) should be 42.0"
                )
            }
        }
    }

    @Test
    fun testPercentileSingleElement() {
        val data = doubleArrayOf(42.0)
        for (p in listOf(0.0, 25.0, 50.0, 75.0, 100.0)) {
            assertEquals(42.0, data.percentile(p), tol, "Single element percentile($p) should be 42.0")
        }
    }

    @Test
    fun testQuantileSelectSingleElement() {
        val data = listOf(99)
        for (method in listOf(
            QuantileMethod.LOWER, QuantileMethod.HIGHER, QuantileMethod.NEAREST,
            QuantileMethod.INVERTED_CDF, QuantileMethod.CLOSEST_OBSERVATION
        )) {
            for (q in listOf(0.0, 0.5, 1.0)) {
                assertEquals(
                    99, data.quantileSelect(q, method),
                    "Single element quantileSelect($q, $method)"
                )
            }
        }
    }

    // ── Edge: two elements ─────────────────────────────────────────────────────

    @Test
    fun testQuantileTwoElementsLinear() {
        val data = doubleArrayOf(3.0, 7.0)
        // h = (n-1)*q + 1 = q + 1
        assertEquals(3.0, data.quantile(0.0, QuantileMethod.LINEAR), tol)
        assertEquals(4.0, data.quantile(0.25, QuantileMethod.LINEAR), tol)
        assertEquals(5.0, data.quantile(0.5, QuantileMethod.LINEAR), tol)
        assertEquals(6.0, data.quantile(0.75, QuantileMethod.LINEAR), tol)
        assertEquals(7.0, data.quantile(1.0, QuantileMethod.LINEAR), tol)
    }

    @Test
    fun testQuantileTwoElementsDiscrete() {
        val data = doubleArrayOf(3.0, 7.0)
        // LOWER: h = (n-1)*q + 1. For q=0.5: h=1.5, floor=1, idx=0 -> 3.0
        assertEquals(3.0, data.quantile(0.5, QuantileMethod.LOWER), tol)
        // HIGHER: ceil(1.5)=2, idx=1 -> 7.0
        assertEquals(7.0, data.quantile(0.5, QuantileMethod.HIGHER), tol)
        // NEAREST: floor(1.5+0.5)=floor(2.0)=2, idx=1 -> 7.0 (rounds half up)
        assertEquals(7.0, data.quantile(0.5, QuantileMethod.NEAREST), tol)
        // MIDPOINT: (3+7)/2 = 5.0
        assertEquals(5.0, data.quantile(0.5, QuantileMethod.MIDPOINT), tol)
    }

    @Test
    fun testQuantileTwoElementsHFMethods() {
        val data = doubleArrayOf(3.0, 7.0)
        // kstats implementation values for q=0.5 on [3, 7]
        assertEquals(3.0, data.quantile(0.5, QuantileMethod.INVERTED_CDF), tol)
        // HF2: h=1.5, h-0.5=1.0, ceil(1.0)=1, idx=0, isDisc=(1.0==floor(1.0))=true -> average
        assertEquals(5.0, data.quantile(0.5, QuantileMethod.AVERAGED_INVERTED_CDF), tol)
        // HF3: h=1.0, bankersRound(1.0)=1, idx=0 -> 3.0
        assertEquals(3.0, data.quantile(0.5, QuantileMethod.CLOSEST_OBSERVATION), tol)
        // HF4: h=1.0, clamped=1.0, j=1, g=0 -> x[0]=3.0
        assertEquals(3.0, data.quantile(0.5, QuantileMethod.INTERPOLATED_INVERTED_CDF), tol)
        // HF5: h=1.5, interpolation between x[0]=3 and x[1]=7: 3+0.5*4=5.0
        assertEquals(5.0, data.quantile(0.5, QuantileMethod.HAZEN), tol)
        // HF6: h=(3)*0.5=1.5, interpolation: 5.0
        assertEquals(5.0, data.quantile(0.5, QuantileMethod.WEIBULL), tol)
        // HF8, HF9: interpolation, result=5.0
        assertEquals(5.0, data.quantile(0.5, QuantileMethod.MEDIAN_UNBIASED), tol)
        assertEquals(5.0, data.quantile(0.5, QuantileMethod.NORMAL_UNBIASED), tol)
    }

    // ── Edge: unsorted input ───────────────────────────────────────────────────

    @Test
    fun testQuantileUnsortedInput() {
        val sortedData = doubleArrayOf(1.0, 2.0, 3.0, 4.0, 5.0)
        val unsortedData = doubleArrayOf(4.0, 2.0, 5.0, 1.0, 3.0)
        for (method in QuantileMethod.entries) {
            for (q in listOf(0.0, 0.25, 0.5, 0.75, 1.0)) {
                assertEquals(
                    sortedData.quantile(q, method),
                    unsortedData.quantile(q, method),
                    tol,
                    "Unsorted data quantile($q, $method) should equal sorted"
                )
            }
        }
    }

    // ── Edge: input array not mutated ──────────────────────────────────────────

    @Test
    fun testQuantileDoesNotMutateInput() {
        val data = doubleArrayOf(5.0, 3.0, 1.0, 4.0, 2.0)
        val original = data.copyOf()
        data.quantile(0.5, QuantileMethod.LINEAR)
        for (i in data.indices) {
            assertEquals(original[i], data[i], 0.0, "Input should not be mutated at index $i")
        }
    }

    // ── Degenerate: empty array ────────────────────────────────────────────────

    @Test
    fun testQuantileEmptyArray() {
        assertFailsWith<InsufficientDataException> {
            doubleArrayOf().quantile(0.5)
        }
    }

    @Test
    fun testQuantileEmptyIterable() {
        assertFailsWith<InsufficientDataException> {
            emptyList<Double>().quantile(0.5)
        }
    }

    @Test
    fun testPercentileEmptyArray() {
        assertFailsWith<InsufficientDataException> {
            doubleArrayOf().percentile(50.0)
        }
    }

    @Test
    fun testQuartilesEmptyArray() {
        assertFailsWith<InsufficientDataException> {
            doubleArrayOf().quartiles()
        }
    }

    @Test
    fun testQuartilesEmptyIterable() {
        assertFailsWith<InsufficientDataException> {
            emptyList<Double>().quartiles()
        }
    }

    @Test
    fun testQuantileSelectEmptyList() {
        assertFailsWith<InsufficientDataException> {
            emptyList<Int>().quantileSelect(0.5)
        }
    }

    @Test
    fun testPercentileSelectEmptyList() {
        assertFailsWith<InsufficientDataException> {
            emptyList<String>().percentileSelect(50.0)
        }
    }

    // ── Degenerate: invalid quantile/percentile parameter ──────────────────────

    @Test
    fun testQuantileOutOfRangeLow() {
        val data = doubleArrayOf(1.0, 2.0, 3.0)
        assertFailsWith<InvalidParameterException> {
            data.quantile(-0.1)
        }
    }

    @Test
    fun testQuantileOutOfRangeHigh() {
        val data = doubleArrayOf(1.0, 2.0, 3.0)
        assertFailsWith<InvalidParameterException> {
            data.quantile(1.1)
        }
    }

    @Test
    fun testPercentileOutOfRangeLow() {
        val data = doubleArrayOf(1.0, 2.0, 3.0)
        assertFailsWith<InvalidParameterException> {
            data.percentile(-1.0)
        }
    }

    @Test
    fun testPercentileOutOfRangeHigh() {
        val data = doubleArrayOf(1.0, 2.0, 3.0)
        assertFailsWith<InvalidParameterException> {
            data.percentile(101.0)
        }
    }

    @Test
    fun testQuantileSelectOutOfRangeLow() {
        val data = listOf(1, 2, 3)
        assertFailsWith<InvalidParameterException> {
            data.quantileSelect(-0.01)
        }
    }

    @Test
    fun testQuantileSelectOutOfRangeHigh() {
        val data = listOf(1, 2, 3)
        assertFailsWith<InvalidParameterException> {
            data.quantileSelect(1.01)
        }
    }

    @Test
    fun testPercentileSelectOutOfRange() {
        val data = listOf(1, 2, 3)
        assertFailsWith<InvalidParameterException> {
            data.percentileSelect(-0.01)
        }
        assertFailsWith<InvalidParameterException> {
            data.percentileSelect(100.01)
        }
    }

    // ── Degenerate: interpolating method passed to quantileSelect ──────────────

    @Test
    fun testQuantileSelectRejectsInterpolatingMethods() {
        val data = listOf(1, 2, 3, 4, 5)
        val interpolating = listOf(
            QuantileMethod.AVERAGED_INVERTED_CDF,
            QuantileMethod.INTERPOLATED_INVERTED_CDF,
            QuantileMethod.HAZEN,
            QuantileMethod.WEIBULL,
            QuantileMethod.LINEAR,
            QuantileMethod.MEDIAN_UNBIASED,
            QuantileMethod.NORMAL_UNBIASED,
            QuantileMethod.MIDPOINT,
        )
        for (method in interpolating) {
            assertFailsWith<InvalidParameterException>("Should reject $method") {
                data.quantileSelect(0.5, method)
            }
        }
    }

    // ── Degenerate: constant data ──────────────────────────────────────────────

    @Test
    fun testQuantileConstantData() {
        val data = doubleArrayOf(7.0, 7.0, 7.0, 7.0, 7.0)
        for (method in QuantileMethod.entries) {
            for (q in listOf(0.0, 0.25, 0.5, 0.75, 1.0)) {
                assertEquals(
                    7.0, data.quantile(q, method), tol,
                    "Constant data quantile($q, $method) should be 7.0"
                )
            }
        }
    }

    @Test
    fun testPercentileConstantData() {
        val data = doubleArrayOf(7.0, 7.0, 7.0, 7.0, 7.0)
        for (p in listOf(0.0, 25.0, 50.0, 75.0, 100.0)) {
            assertEquals(7.0, data.percentile(p), tol, "Constant data percentile($p) should be 7.0")
        }
    }

    @Test
    fun testQuartilesConstantData() {
        val data = doubleArrayOf(7.0, 7.0, 7.0, 7.0, 7.0)
        val (q1, q2, q3) = data.quartiles()
        assertEquals(7.0, q1, tol)
        assertEquals(7.0, q2, tol)
        assertEquals(7.0, q3, tol)
    }

    // ── Extreme: large offset data ─────────────────────────────────────────────

    @Test
    fun testQuantileLargeOffsetData() {
        val data = doubleArrayOf(1e15, 1e15 + 1.0, 1e15 + 2.0, 1e15 + 3.0, 1e15 + 4.0)
        assertEquals(1e15, data.quantile(0.0), tol)
        assertEquals(1e15 + 2.0, data.quantile(0.5), tol)
        assertEquals(1e15 + 4.0, data.quantile(1.0), tol)
    }

    @Test
    fun testQuantileLargeNegativeValues() {
        val data = doubleArrayOf(-1e15, -1e14, -1e13, -1e12, -1e11)
        assertEquals(-1e15, data.quantile(0.0), tol)
        assertEquals(-1e13, data.quantile(0.5), tol)
        assertEquals(-1e11, data.quantile(1.0), tol)
    }

    @Test
    fun testQuantileVerySmallDifferences() {
        val base = 1.0
        val data = DoubleArray(5) { base + it * 1e-14 }
        val result = data.quantile(0.5)
        assertTrue(result.isFinite(), "Quantile with tiny differences should be finite")
        assertTrue(result >= data[0], "Quantile should be >= min")
        assertTrue(result <= data[4], "Quantile should be <= max")
    }

    @Test
    fun testQuantileLargeArray() {
        val data = DoubleArray(10000) { it.toDouble() }
        // numpy: np.quantile(np.arange(10000), 0.5) = 4999.5
        assertEquals(4999.5, data.quantile(0.5), tol)
        assertEquals(0.0, data.quantile(0.0), tol)
        assertEquals(9999.0, data.quantile(1.0), tol)
    }

    // ── Non-finite: NaN handling ───────────────────────────────────────────────

    @Test
    fun testQuantileNaNInDataLinear() {
        // When NaN is in data, the result depends on where introSelect places NaN.
        // NaN comparisons are always false in IEEE 754, so the result may be NaN
        // or a finite value depending on the q and the method.
        // The key property: the function should not throw an exception.
        val data = doubleArrayOf(1.0, Double.NaN, 3.0, 4.0, 5.0)
        val result = data.quantile(0.5)
        // Result may be NaN or a data element — just verify no exception
        assertTrue(result.isNaN() || result.isFinite(), "quantile(0.5) with NaN should not crash")
    }

    @Test
    fun testQuantileNaNParameter() {
        val data = doubleArrayOf(1.0, 2.0, 3.0, 4.0, 5.0)
        // NaN is not in [0, 1] per IEEE 754 (NaN !in 0.0..1.0 is true)
        assertFailsWith<InvalidParameterException> {
            data.quantile(Double.NaN)
        }
    }

    @Test
    fun testPercentileNaNParameter() {
        val data = doubleArrayOf(1.0, 2.0, 3.0, 4.0, 5.0)
        // NaN is not in [0, 100]
        assertFailsWith<InvalidParameterException> {
            data.percentile(Double.NaN)
        }
    }

    @Test
    fun testQuantileNaNInDataAllMethods() {
        val data = doubleArrayOf(1.0, 2.0, Double.NaN, 4.0, 5.0)
        for (method in QuantileMethod.entries) {
            val result = data.quantile(0.5, method)
            // NaN in data may or may not propagate depending on introSelect behavior.
            // Just verify no exception is thrown.
            assertTrue(
                result.isNaN() || result.isFinite(),
                "quantile(0.5, $method) with NaN should not crash"
            )
        }
    }

    @Test
    fun testQuantilePositiveInfinityInData() {
        val data = doubleArrayOf(1.0, 2.0, Double.POSITIVE_INFINITY, 4.0, 5.0)
        // When +Inf is in the data, quantile should still work
        val result = data.quantile(0.5)
        assertTrue(result.isFinite() || result.isInfinite(), "quantile with +Inf should not be NaN")
    }

    @Test
    fun testQuantileNegativeInfinityInData() {
        val data = doubleArrayOf(Double.NEGATIVE_INFINITY, 2.0, 3.0, 4.0, 5.0)
        // q=0 with any method that returns min should give -Inf
        val result = data.quantile(0.0)
        assertEquals(Double.NEGATIVE_INFINITY, result)
    }

    @Test
    fun testQuantileSelectNaNParameter() {
        val data = listOf(1, 2, 3)
        assertFailsWith<InvalidParameterException> {
            data.quantileSelect(Double.NaN)
        }
    }

    @Test
    fun testPercentileSelectNaNParameter() {
        val data = listOf(1, 2, 3)
        assertFailsWith<InvalidParameterException> {
            data.percentileSelect(Double.NaN)
        }
    }

    // ── Property: quantile monotonicity ────────────────────────────────────────

    @Test
    fun testQuantileMonotonicity() {
        val data = doubleArrayOf(3.0, 1.0, 4.0, 1.0, 5.0, 9.0, 2.0, 6.0)
        val qs = listOf(0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0)
        for (method in QuantileMethod.entries) {
            val values = qs.map { data.quantile(it, method) }
            for (i in 0 until values.size - 1) {
                assertTrue(
                    values[i] <= values[i + 1],
                    "Monotonicity violated: quantile(${qs[i]}, $method)=${values[i]} > quantile(${qs[i + 1]}, $method)=${values[i + 1]}"
                )
            }
        }
    }

    // ── Property: all quantile values are within data range ────────────────────

    @Test
    fun testQuantileWithinDataRange() {
        val data = doubleArrayOf(3.0, 1.0, 4.0, 1.0, 5.0, 9.0, 2.0, 6.0)
        val minVal = data.min()
        val maxVal = data.max()
        for (method in QuantileMethod.entries) {
            for (q in listOf(0.0, 0.1, 0.25, 0.5, 0.75, 0.9, 1.0)) {
                val result = data.quantile(q, method)
                assertTrue(result >= minVal, "quantile($q, $method) = $result should be >= min=$minVal")
                assertTrue(result <= maxVal, "quantile($q, $method) = $result should be <= max=$maxVal")
            }
        }
    }

    // ── Property: quantile(0) = min, quantile(1) = max for non-averaging methods

    @Test
    fun testQuantileZeroIsMinOneIsMax() {
        val data = doubleArrayOf(3.0, 1.0, 4.0, 1.0, 5.0, 9.0, 2.0, 6.0)
        val minVal = data.min()
        val maxVal = data.max()
        // AVERAGED_INVERTED_CDF may not return min at q=0 (averages at discontinuity)
        val methods = QuantileMethod.entries.filter { it != QuantileMethod.AVERAGED_INVERTED_CDF }
        for (method in methods) {
            assertEquals(
                minVal, data.quantile(0.0, method), tol,
                "quantile(0, $method) should be min"
            )
            assertEquals(
                maxVal, data.quantile(1.0, method), tol,
                "quantile(1, $method) should be max"
            )
        }
    }

    // ── Property: LOWER <= LINEAR <= HIGHER ────────────────────────────────────

    @Test
    fun testLowerLinearHigherOrdering() {
        val data = doubleArrayOf(3.0, 1.0, 4.0, 1.0, 5.0, 9.0, 2.0, 6.0)
        for (q in listOf(0.0, 0.1, 0.25, 0.5, 0.75, 0.9, 1.0)) {
            val lower = data.quantile(q, QuantileMethod.LOWER)
            val linear = data.quantile(q, QuantileMethod.LINEAR)
            val higher = data.quantile(q, QuantileMethod.HIGHER)
            assertTrue(
                lower <= linear,
                "LOWER($q)=$lower should be <= LINEAR($q)=$linear"
            )
            assertTrue(
                linear <= higher,
                "LINEAR($q)=$linear should be <= HIGHER($q)=$higher"
            )
        }
    }

    // ── Property: MIDPOINT = (LOWER + HIGHER) / 2 ─────────────────────────────

    @Test
    fun testMidpointIsAverageOfLowerHigher() {
        val data = doubleArrayOf(3.0, 1.0, 4.0, 1.0, 5.0, 9.0, 2.0, 6.0)
        for (q in listOf(0.0, 0.1, 0.25, 0.5, 0.75, 0.9, 1.0)) {
            val lower = data.quantile(q, QuantileMethod.LOWER)
            val higher = data.quantile(q, QuantileMethod.HIGHER)
            val midpoint = data.quantile(q, QuantileMethod.MIDPOINT)
            assertEquals(
                (lower + higher) / 2.0, midpoint, tol,
                "MIDPOINT($q) should be (LOWER+HIGHER)/2"
            )
        }
    }

    // ── Property: LOWER and HIGHER are always data elements ────────────────────

    @Test
    fun testLowerHigherAreDataElements() {
        val data = doubleArrayOf(3.0, 1.0, 4.0, 1.0, 5.0, 9.0, 2.0, 6.0)
        val sortedData = data.sorted()
        for (q in listOf(0.0, 0.1, 0.25, 0.5, 0.75, 0.9, 1.0)) {
            val lower = data.quantile(q, QuantileMethod.LOWER)
            val higher = data.quantile(q, QuantileMethod.HIGHER)
            assertTrue(lower in sortedData, "LOWER($q) = $lower should be a data element")
            assertTrue(higher in sortedData, "HIGHER($q) = $higher should be a data element")
        }
    }

    // ── Property: NEAREST is always a data element ─────────────────────────────

    @Test
    fun testNearestIsDataElement() {
        val data = doubleArrayOf(3.0, 1.0, 4.0, 1.0, 5.0, 9.0, 2.0, 6.0)
        val sortedData = data.sorted()
        for (q in listOf(0.0, 0.1, 0.25, 0.5, 0.75, 0.9, 1.0)) {
            val nearest = data.quantile(q, QuantileMethod.NEAREST)
            assertTrue(nearest in sortedData, "NEAREST($q) = $nearest should be a data element")
        }
    }

    // ── Property: INVERTED_CDF and CLOSEST_OBSERVATION are always data elements

    @Test
    fun testDiscreteMethodsReturnDataElements() {
        val data = doubleArrayOf(3.0, 1.0, 4.0, 1.0, 5.0, 9.0, 2.0, 6.0)
        val sortedData = data.sorted()
        val discreteMethods = listOf(
            QuantileMethod.INVERTED_CDF,
            QuantileMethod.CLOSEST_OBSERVATION,
            QuantileMethod.LOWER,
            QuantileMethod.HIGHER,
            QuantileMethod.NEAREST,
        )
        for (method in discreteMethods) {
            for (q in listOf(0.0, 0.1, 0.25, 0.5, 0.75, 0.9, 1.0)) {
                val result = data.quantile(q, method)
                assertTrue(result in sortedData, "$method($q) = $result should be a data element")
            }
        }
    }

    // ── Property: quantile symmetry ────────────────────────────────────────────

    @Test
    fun testQuantileSymmetry() {
        // Symmetric data: quantile(q) + quantile(1-q) should be constant for interpolation methods
        val data = doubleArrayOf(1.0, 3.0, 5.0, 7.0, 9.0)
        val center = 5.0
        val symmetricMethods = listOf(
            QuantileMethod.LINEAR,
            QuantileMethod.HAZEN,
            QuantileMethod.WEIBULL,
            QuantileMethod.MEDIAN_UNBIASED,
            QuantileMethod.NORMAL_UNBIASED,
            QuantileMethod.MIDPOINT,
        )
        for (method in symmetricMethods) {
            for (q in listOf(0.1, 0.25, 0.4)) {
                val low = data.quantile(q, method)
                val high = data.quantile(1.0 - q, method)
                assertEquals(
                    2 * center, low + high, tol,
                    "For symmetric data, quantile($q) + quantile(${1 - q}) = ${2 * center} using $method"
                )
            }
        }
    }

    // ── Property: quantileSelect consistency with Double quantile ───────────────

    @Test
    fun testQuantileSelectConsistentWithDoubleQuantile() {
        val doubleData = doubleArrayOf(10.0, 30.0, 50.0, 70.0, 90.0)
        val intData = listOf(10, 30, 50, 70, 90)
        val nonInterpMethods = listOf(
            QuantileMethod.LOWER, QuantileMethod.HIGHER, QuantileMethod.NEAREST,
            QuantileMethod.INVERTED_CDF, QuantileMethod.CLOSEST_OBSERVATION,
        )
        for (method in nonInterpMethods) {
            for (q in listOf(0.0, 0.25, 0.5, 0.75, 1.0)) {
                assertEquals(
                    doubleData.quantile(q, method),
                    intData.quantileSelect(q, method).toDouble(),
                    tol,
                    "quantileSelect($q, $method) should be consistent with Double quantile"
                )
            }
        }
    }

    // ── Property: percentile(p) = quantile(p/100) ─────────────────────────────

    @Test
    fun testPercentileQuantileRelation() {
        val data = doubleArrayOf(3.0, 1.0, 4.0, 1.0, 5.0, 9.0)
        for (method in QuantileMethod.entries) {
            for (p in listOf(0.0, 25.0, 50.0, 75.0, 100.0)) {
                assertEquals(
                    data.quantile(p / 100.0, method),
                    data.percentile(p, method),
                    tol,
                    "percentile($p, $method) = quantile(${p / 100.0}, $method)"
                )
            }
        }
    }

    // ── Property: percentileSelect(p) = quantileSelect(p/100) ─────────────────

    @Test
    fun testPercentileSelectQuantileSelectRelation() {
        val data = listOf("a", "b", "c", "d", "e")
        val nonInterpMethods = listOf(
            QuantileMethod.LOWER, QuantileMethod.HIGHER, QuantileMethod.NEAREST,
            QuantileMethod.INVERTED_CDF, QuantileMethod.CLOSEST_OBSERVATION,
        )
        for (method in nonInterpMethods) {
            for (p in listOf(0.0, 25.0, 50.0, 75.0, 100.0)) {
                assertEquals(
                    data.quantileSelect(p / 100.0, method),
                    data.percentileSelect(p, method),
                    "percentileSelect($p, $method) = quantileSelect(${p / 100.0}, $method)"
                )
            }
        }
    }

    // ── Property: quartiles = (quantile(0.25), quantile(0.5), quantile(0.75)) ─

    @Test
    fun testQuartilesConsistencyWithQuantile() {
        val data = doubleArrayOf(3.0, 1.0, 4.0, 1.0, 5.0, 9.0, 2.0, 6.0)
        for (method in QuantileMethod.entries) {
            val (q1, q2, q3) = data.quartiles(method)
            assertEquals(
                data.quantile(0.25, method), q1, tol,
                "quartiles.$method Q1 should equal quantile(0.25)"
            )
            assertEquals(
                data.quantile(0.50, method), q2, tol,
                "quartiles.$method Q2 should equal quantile(0.50)"
            )
            assertEquals(
                data.quantile(0.75, method), q3, tol,
                "quartiles.$method Q3 should equal quantile(0.75)"
            )
        }
    }

    // ── Property: quantileSelect with Comparable types ─────────────────────────

    @Test
    fun testQuantileSelectWithCustomComparable() {
        data class Score(val value: Int) : Comparable<Score> {
            override fun compareTo(other: Score) = value.compareTo(other.value)
        }

        val data = listOf(Score(10), Score(30), Score(20), Score(50), Score(40))
        assertEquals(Score(30), data.quantileSelect(0.5, QuantileMethod.NEAREST))
        assertEquals(Score(10), data.quantileSelect(0.0, QuantileMethod.LOWER))
        assertEquals(Score(50), data.quantileSelect(1.0, QuantileMethod.HIGHER))
    }

    // ── Golden: dense grid LINEAR on [15, 20, 35, 40, 50] ─────────────────────

    @Test
    fun testQuantileLinearGoldenValues() {
        // Golden values: np.quantile([15,20,35,40,50], q, method='linear')
        val data = doubleArrayOf(15.0, 20.0, 35.0, 40.0, 50.0)
        val qs = doubleArrayOf(0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0)
        val expected = doubleArrayOf(
            15.0, 17.0, 19.0, 23.0, 29.0, 35.0, 37.0, 39.0, 42.0, 46.0, 50.0
        )
        for (i in qs.indices) {
            assertEquals(
                expected[i], data.quantile(qs[i], QuantileMethod.LINEAR), tol,
                "LINEAR quantile(${qs[i]})"
            )
        }
    }

    // ── Deprecated API: QuantileInterpolation ──────────────────────────────────

    @Suppress("DEPRECATION")
    @Test
    fun testDeprecatedQuantileInterpolationCompatibility() {
        val data = doubleArrayOf(1.0, 2.0, 3.0, 4.0)
        assertEquals(
            data.quantile(0.25, QuantileMethod.LINEAR),
            data.quantile(0.25, QuantileInterpolation.LINEAR),
            tol
        )
        assertEquals(
            data.quantile(0.25, QuantileMethod.LOWER),
            data.quantile(0.25, QuantileInterpolation.LOWER),
            tol
        )
        assertEquals(
            data.quantile(0.25, QuantileMethod.HIGHER),
            data.quantile(0.25, QuantileInterpolation.HIGHER),
            tol
        )
        assertEquals(
            data.quantile(0.25, QuantileMethod.NEAREST),
            data.quantile(0.25, QuantileInterpolation.NEAREST),
            tol
        )
        assertEquals(
            data.quantile(0.25, QuantileMethod.MIDPOINT),
            data.quantile(0.25, QuantileInterpolation.MIDPOINT),
            tol
        )
    }

    @Suppress("DEPRECATION")
    @Test
    fun testDeprecatedPercentileInterpolationCompatibility() {
        val data = doubleArrayOf(1.0, 2.0, 3.0, 4.0)
        assertEquals(
            data.percentile(25.0, QuantileMethod.LOWER),
            data.percentile(25.0, QuantileInterpolation.LOWER),
            tol
        )
        assertEquals(
            data.percentile(25.0, QuantileMethod.HIGHER),
            data.percentile(25.0, QuantileInterpolation.HIGHER),
            tol
        )
    }

    @Suppress("DEPRECATION")
    @Test
    fun testDeprecatedIterablePercentileCompatibility() {
        val data = listOf(1.0, 2.0, 3.0, 4.0)
        assertEquals(
            data.percentile(25.0, QuantileMethod.LINEAR),
            data.percentile(25.0, QuantileInterpolation.LINEAR),
            tol
        )
    }

    @Suppress("DEPRECATION")
    @Test
    fun testDeprecatedSequenceQuantileCompatibility() {
        val data = sequenceOf(1.0, 2.0, 3.0, 4.0)
        val list = listOf(1.0, 2.0, 3.0, 4.0)
        assertEquals(
            list.quantile(0.5, QuantileMethod.LINEAR),
            data.quantile(0.5, QuantileInterpolation.LINEAR),
            tol
        )
    }
}
